# -*- mode: python ; coding: utf-8 -*-

import os
from pathlib import Path

ROOT = Path(SPECPATH).resolve()
BUILD_INFO = Path(os.environ.get('RETIREMENT_PET_BUILD_INFO', ''))
BUILD_MODULE_DIR = Path(os.environ.get('RETIREMENT_PET_BUILD_MODULE_DIR', ''))
if not BUILD_INFO.is_file():
    raise SystemExit(
        'RETIREMENT_PET_BUILD_INFO must name metadata generated by '
        'scripts/release_identity.py')
if not (BUILD_MODULE_DIR / 'retirement_pet_build_info.py').is_file():
    raise SystemExit(
        'RETIREMENT_PET_BUILD_MODULE_DIR must contain the generated '
        'retirement_pet_build_info module')

a = Analysis(
    [str(ROOT / 'src' / 'retirement_pet' / 'main.py')],
    pathex=[str(ROOT / 'src'), str(BUILD_MODULE_DIR)],
    binaries=[],
    datas=[(str(ROOT / 'assets'), 'assets'),
           (str(ROOT / 'config'), 'config'),
           (str(ROOT / 'LICENSE'), '.'),
           (str(ROOT / 'THIRD_PARTY_NOTICES.md'), '.'),
           (str(ROOT / 'docs' / 'LICENSING.md'), 'docs'),
           (str(BUILD_INFO), '.')],
    hiddenimports=['retirement_pet_build_info'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['PySide6.QtQml', 'PySide6.QtQuick', 'PySide6.QtQuick3D', 'PySide6.QtQuickWidgets', 'PySide6.QtQuickControls2', 'PySide6.QtPdf', 'PySide6.QtPdfWidgets', 'PySide6.QtVirtualKeyboard', 'PySide6.QtSvg', 'PySide6.QtSvgWidgets', 'PySide6.QtPrintSupport', 'PySide6.QtSql', 'PySide6.QtTest', 'PySide6.QtXml', 'PySide6.QtConcurrent', 'PySide6.QtStateMachine', 'PySide6.QtCharts', 'PySide6.QtDataVisualization', 'PySide6.QtGraphs', 'PySide6.Qt3DCore', 'PySide6.Qt3DRender', 'PySide6.Qt3DInput', 'PySide6.Qt3DLogic', 'PySide6.Qt3DAnimation', 'PySide6.Qt3DExtras', 'PySide6.QtWebEngineCore', 'PySide6.QtWebEngineWidgets', 'PySide6.QtWebChannel', 'PySide6.QtWebSockets', 'PySide6.QtNfc', 'PySide6.QtBluetooth', 'PySide6.QtPositioning', 'PySide6.QtLocation', 'PySide6.QtSensors', 'PySide6.QtSerialPort', 'PySide6.QtTextToSpeech', 'PySide6.QtUiTools', 'PySide6.QtHelp', 'PySide6.QtDesigner', 'PySide6.QtMultimediaWidgets', 'PySide6.QtOpenGLWidgets', 'PySide6.QtScxml', 'PySide6.QtHttpServer', 'PySide6.QtDBus', 'PySide6.QtRemoteObjects', 'PySide6.QtProtocol'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='RetirementPet',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version=str(ROOT / 'scripts' / 'version_info.txt'),
    icon=[str(ROOT / 'assets' / 'icons' / 'retirement_pet.ico')],
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='RetirementPet',
)
